### ISSUE TITLE
14 contigs recieved from SMRTportal using HGAP.3

### ISSUE THREAD

**Issue by komwit** [PacificBiosciences/Bioinformatics-Training#24]
Hi,
I try to assembly my Lactobacillus genome in HGAP.3 using SMRTPortal. I set genome size about 3000000 bp and use coverage at 15x. I do not adjust any other parameter and I got 14 contigs as a result.  The max contig length	 is 1,970,329. Sum of Contig Lengths is	3,111,026

Do you have any recommendation for adjusting the parameter to produce less contig than this?
Hopefully you can give me some advice. I started aws last few days ago and I am running out of budget now. Thank you.

Polished Contigs 14
Adapter Dimers (0-10bp) 0.01%
Short Inserts (11-100bp) 0.0%
Number of Bases 829,596,363
Number of Reads 76,328
N50 Read Length 20,810
Mean Read Length 10,868
Mean Read Score 0.84
Mapped Reads 68,969
Mapped Read Length of Insert 4,333
Average Reference Length 222,207
Average Reference Bases Called 100.0%
Average Reference Consensus Concordance 99.98%
Average Reference Coverage 191.48

**Comment by rhallPB** [comment]
What do your subread stats looks like, Mean length, N50?
What are the PreAssembled read stats, length cut, yield etc.?
Thanks.

**Comment by komwit** [comment]
Hi, now I got only 15 contigs by using HGAP.2 by reducing Minimum Subread Length to 100, Minimum Seed Read Length to 2000 and using 15x coverage with genome size 3200000 bp. 
Below is more detail about pre-assembly,

Polymerase Read Bases	825,956,037	Length Cutoff	11,024
Seed Bases	96,007,134	                Pre-Assembled bases	36,894,385
Pre-Assembled Yield	.384	                Pre-Assembled Reads	6,472
Pre-Assembled Reads Length	5,700	Pre-Assembled N50	        7,148

Mapped Subread Length N50 (bp)	6,204	       
Mapped Polymerase Read Length 95% (bp)	32,250
Mapped Subread Length Mean (bp)	4,695	
Mapped Polymerase Read Length Max (bp)	47,859


Do you have any suggestion for improve my assembly results? Thank you :)

**Comment by rhallPB** [comment]
The Pre-Assembled yield is too low, indicating that something is not right. I think that that the input coverage is too high for the automatically generated seed cutoff to be a optimal. Are the 825Mb from only one cell? If it's from two I would first start with assembling only one cell, using default parameters. Otherwise I would run HGAP.3 with default parameters, but not automatically generating the seed length (uncheck box), set it to 5kb and the `Minimum Coverage For Correction`  to 8. 

The reason that too much coverage causes issues is that the seed length is automatically set at 30x of the estimated genome size. Given really high coverage this length is in the extreme of the length distribution, where, if the DNA was not really fragmented to a large size, the chances of a read being a biological chimera is high. This results in a lot of the seed reads not getting corrected and the yield for preassembled reads is low and there is not enough coverage going into assembly.

**Comment by komwit** [comment]
Yes, it came from only one cell. Now, I am running HGAP.3 by using your suggestions. If the assembly is right, what's the Pre-Assembled yield about?

**Comment by rhallPB** [comment]
For default parameters yield should be ~70%, for great data it can be >80%, I worry if it's less than 60%.
Under the above conditions / parameters the yield will be less meaningful, but you should look for the `Pre-Assembled bases` to be around 75,000,000, and certainly no less than 50,000,000.

**Comment by komwit** [comment]
Hi, again. I followed your recommendations and now I got 
Polymerase Read Bases	761,038,162	
Length Cutoff	5,000
Seed Bases	602,670,550	
Pre-Assembled bases	123,038,316
Pre-Assembled Yield	.204	
Pre-Assembled Reads	28,582
Pre-Assembled Reads Length	4,304	
Pre-Assembled N50	6,537

Is it look quite bad? how can I improve the result?

**Comment by rhallPB** [comment]
Are you using a cutoff in the filtering step other than default? The results don't look too bad, ignoring the yield the preassembled based looks good, although a little high. It is probably worth letting this run through assembly, or you could increase the coverage required for correction to try to reduce the number of bases going into assembly closer to 75,000,000.


On Feb 18, 2016, at 6:40 AM, komwit <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, again. I followed your recommendations and now I got
Polymerase Read Bases 761,038,162
Length Cutoff 5,000
Seed Bases 602,670,550
Pre-Assembled bases 123,038,316
Pre-Assembled Yield .204

Pre-Assembled Reads 28,582
Pre-Assembled Reads Length 4,304

Pre-Assembled N50 6,537

Is it look quite bad? how can I improve the result?

**Comment by komwit** [comment]
> Are you using a cutoff in the filtering step other than default?
No, i used default value. 

<img width="581" alt="screen shot 2559-02-19 at 07 13 34" src="https://cloud.githubusercontent.com/assets/16858788/13162579/4fa395b8-d6d8-11e5-9d9d-c6306323aea5.png">
<img width="529" alt="screen shot 2559-02-19 at 07 13 08" src="https://cloud.githubusercontent.com/assets/16858788/13162582/54cc1060-d6d8-11e5-9995-e481249c8b5b.png">

The result reduce to 9 contigs. The Consensus Concordance of the top length is 99.9905% with coverage 192.76. Is that okay now?

**Comment by rhallPB** [comment]
The consensus concordance isn't really meaningful at this point of the analysis. It looks like the 3Mb contig is the complete genome. I would suggest checking to see is it is circular [https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/Evaluating-Assemblies](url)
[https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/Circularizing-and-trimming](url)
[http://biorxiv.org/content/early/2015/07/28/023408](url)
It is probably worth checking the other contigs for circularity and a quick blast to see if they are obviously 'junk' (palindromic contigs can be formed due to missing adapters in the library), with the extra coverage and the parameters used it is likely that some 'junk' contigs were generated. The 1,294x coverage contig looks interesting, it is either a highly repetitive element, that was not incorporated into the assembly, or a high copy number plasmid Looking at how the reads align back to the assembled contigs can be very informative, also the bridgemapper protocol can help with visualization and the manual checking of contigs.

**Comment by komwit** [comment]
Thank you for your help. That's very helpful for newbie like me. 

Thank you very much.

**Comment by pb-cdunn** [comment]
Helpful to me too, @rhallPB. I just read all your links, and then some. That cleared up a lot for me. And [bridgemapper](https://s3.amazonaws.com/files.pacb.com/software/smrtanalysis/2.1.0/Doc/smrtview/help/Webhelp/App_View_Epipro.htm) seems quite useful.

We will have preassembly reports for HGAP.4 in smrtlink (or whatever it's called now) within a week. Coding is done. Can you explain SMRTportal vs. smrtlink?

**Comment by komwit** [comment]
Hi again, @rhallPB 
I followed your recommendation from previous comment to reduce Pre-Assembled bases to around   75,000,000. I set the Length Cutoff 5,000 and the Minimum Coverage For Correction to 15 and i got around 74,620,028. 

Polymerase Read Bases	761,038,162	
Length Cutoff	5,000
Seed Bases	602,670,550	
Pre-Assembled bases	74,620,028
Pre-Assembled Yield	.124	
Pre-Assembled Reads	22,624
Pre-Assembled Reads Length	3,298	
Pre-Assembled N50	6,072

 Here is my result.
![1](https://cloud.githubusercontent.com/assets/16858788/16451737/00df005c-3e2f-11e6-8908-4847830eed5a.png)

Then I try to follow you to do (https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/Evaluating-Assemblies). I have some questions about reference file. What is lambda.fasta from? Is it available from assembly results?

Thank you for your kindness.

**Comment by ptmckenney** [comment]
I have a quick question on this as well:

@rhallPB Why did you choose 5000 for the Length cutoff?

Thank you.

**Comment by rhallPB** [comment]
@komwit I would blast the contigs in your latest results, from the coverage it looks like unitig_121 is a high copy number plasmid. 
lambda.fasta is just the reference fasta, in this case you polished assembly.

@ptmckenney I suggested 5000 because the high level of coverage skewed the auto setting of the seed length in the original run.
