### ISSUE TITLE
the assembly genome complementness

### ISSUE THREAD

**Issue by yilunhuangyue** [PacificBiosciences/Bioinformatics-Training#26]
Hello, I have assembly a genome using HGAP in SMRT-analysis. Everything is well except the complementness of the genome. The estimate genome size is 380M but the assemblied contig is less 340M. And I have identified the complementness by CEGMA and BUSCO. Both of the results are not good. Are there any parameters can be adjusted to improve the complementness of the assemblied contig? Thanks a lot.

**Comment by rhallPB** [comment]
What coverage of raw reads did you have going into assembly? What was the preassembled yield? What is the assembly N50?
Assembling 90% of the expected genome size for a 380Mb organism is not unreasonable, as it's likely plant of fungus? the remaining 10% could easily be highly repetitive, low complexity sequence that does not assemble.
What % or raw reads align to the assembly when resequencing / quiver correcting? You may want to check the unmapped reads for repetitive content, complexity. Rather than try to improve the completeness with changing parameters, I would use a different assembler to see if the results are different, [canu ](https://github.com/marbl/canu) or [Falcon](https://github.com/PacificBiosciences/FALCON) would be my first choices.
How are you finding the CEGMA genes, do you have a set of genes from a close relative, or are you using the gene models in the BUSCO pipeline. My personal experience is that the BUSCO pipeline does not perform equally well across all organisms. I've seen consistent ~60% completeness for BUSCO, even when other methods suggest that the assemblies are very complete for a particular order of vertebrates.

**Comment by yilunhuangyue** [comment]
Thanks for your reply. I will try other methods and compare the results.
