### ISSUE TITLE
More protocols

### ISSUE THREAD

**Issue by 2waybene** [PacificBiosciences/Bioinformatics-Training#28]
I installed this virtual machine via vagrant, but only see six protocols loaded. How can I get more protocols loaded? Thanks

**Comment by rhallPB** [comment]
What are the six protocols that you see?

**Comment by 2waybene** [comment]
RS_AHA_Scaffolding.1
RS_HGAP_Assembly.2
RS_HGAP_Assembly.3
RS_IsoSeq.1
RS_Long_Amplicao_Analysis.1
RS_PreAssembler.2

**Comment by rhallPB** [comment]
Sorry, I'm not sure why that happened, it should be complete with all the protocols. I'll check the VM, did you follow:
https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/SMRT-Analysis-Virtual-Machine-Install

**Comment by 2waybene** [comment]
Yes, I followed all the steps listed at the github. Well, that how I got it to work. The problem is that I have six protocols but not all. BTW, how many are we supposed to have? It seems to me that some files (on your server) used during the installation may got messed up somehow, as a results some protocols did not get loaded. Make sense?

**Comment by rhallPB** [comment]
I figured it out. The protocols are not getting displayed due to the "Which type(s) of analysis would you like to perform on your sequencing data?" dialogue, to see all the protocols you need to select "Display all types of analysis", if you cannot get back to the dialogue go to "account" and restore setting, then the dialogue should return the next time you try to select a protocol. There are ~19 protocols.

**Comment by mhsieh** [comment]
<a target='_BLANK' href='https://ipfs.pics/QmdL8i2nQvy8pighSTivXnrLw33BtXJorKrcPvPHMeBjvP'><img src='https://ipfs.pics/ipfs/QmdL8i2nQvy8pighSTivXnrLw33BtXJorKrcPvPHMeBjvP'/></a>

**Comment by 2waybene** [comment]
Thanks. I did and I was able to see all protocols. Total 17 protocols.
