### ISSUE TITLE
HGAP terminology unclear: subread / single pass read / seed read?

### ISSUE THREAD

**Issue by AnnaSyme** [PacificBiosciences/Bioinformatics-Training#30]
From "Pre-Assembly"
https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/HGAP#hgap-workflow

"This is accomplished by mapping single pass reads to seed reads, which represent the longest portion of the read length distribution. "

Could you please clarify the difference between a single pass read and a seed read? Is a single pass read the same as a subread? Are all reads considered to be "single pass", and the shorter ones are mapped to the longer ones (= "seed reads")?  Thanks.

Any help appreciated!

**Comment by pb-cdunn** [comment]
An insert in a smrt-cell is a ring with an "adapter" at each end. An enzyme will read in a circle: one strand, then, one adapter, then the other strand (backwards), then the other adapter, and repeating with the first strand, etc. It can do that indefinitely (until the machine is stopped or some chemistry breaks down). Typically, we use only a single pass of the entire read for HGAP because any chimerical material would cause specious reinforcement. In theory, with high enough coverage, *other* inserts will provide correctable reinforcement, so excluding extra passes for a given insert should not be a significant loss.

**Comment by AnnaSyme** [comment]
Thank you for your answer! 

Could you confirm if I am understanding this correctly:
- a "single pass read" is a read between two adapters. There are therefore, usually, many single pass reads within one polymerase read. 
- A single pass read is the same as a subread. 
- Single pass reads can vary in length. Long ones (chosen to some value) are called seed reads. 

Thanks if you can help!
Anna

**Comment by pb-cdunn** [comment]
Yes, that's my understanding of the current nomenclature.

**Comment by AnnaSyme** [comment]
Closed - Thanks for your help.
