### ISSUE TITLE
assembly problems by Dihaploid data

### ISSUE THREAD

**Issue by yilunhuangyue** [PacificBiosciences/Bioinformatics-Training#32]
Hi，
    I have assembled a genome by Dihaploid data, the genoem size is about 360M, but the polished_assembly.fasta I got is more than 400M, Is this problem caused by repeat region?what should I do to solve it?
    Thanks a lot.

**Comment by skingan** [comment]
It would be helpful to know more about the organism you sequenced, how the sample was prepared, and what assembler you used.

Its possible that your estimated genome size is wrong. If it is based on a previous assembly, the new PacBio assembly may include more repetitive regions that could not be assembled with other technologies. If the genome size was estimated by another method like flow cytometry, discrepancies with sequenced genome size is not unexpected. See table 4 of this paper: http://labs.biology.ucsd.edu/markow/articles/Bosco%20et%20al%20final.pdf

We have seen instances of genome sizes longer than expectations for interesting biological reasons as well. For diploid organisms, the assembled genome length might be as much as 2X the haploid length due to high divergence between parental chromosomes (http://biorxiv.org/content/biorxiv/early/2016/06/03/056887.full.pdf). But this seems unlikely in a dihaploid sample. It is possible that the mitochondria or chloroplast populations contain multiple, divergent genome sequences, but I'm not sure that could account for a 40Mb size discrepancy.

To test whether there are divergent haplotypes being assembled as separate contigs,there are a few things you can do, in order of how easy they are to do:

1.  Look for contigs that have coverage that is half the genome average 
2. Annotate your genome with the plant BUSCO gene set (http://busco.ezlab.org/) and look for genes that are duplicated in your assembly (https://github.com/skingan/HomolContigsByAnnotation)
3. Do a pairwise alignment of all of your contigs to see if there are any pairs showing high alignment scores, which may represent contigs assembled from divergent homologous chromosomes. HaploMerger (http://genome.cshlp.org/content/22/8/1581.long) is a program designed to do this, or you could use mummer (http://mummer.sourceforge.net/) to do it yourself.

Good luck,
Sarah

**Comment by yilunhuangyue** [comment]
thanks for your reply. I assembled the genome using pacbio reads by HGAP in SMRT . I haved maped the reads sequenced by pacbio and illumina respectly, and when using pacbio reads, the whole genome could be mapped, but when using illumina reads,there are some contigs that can't be mapped(mapping depth is 0). Is these regions be repeat sequence that can't be sequenced in illumina reads?

**Comment by skingan** [comment]
Yes, those are likely repetitive regions or regions with high GC bias. Can you look at the contig sequence and estimate GC% or look for repeats? Where did your original genome size estimate come from?
Sarah
