### ISSUE TITLE
minimus2 fails during circularisation

### ISSUE THREAD

**Issue by mjfi2sb3** [PacificBiosciences/Bioinformatics-Training#35]
Hi,
I am trying to circularise a bacterial genome. However, minimus2 fails with the following error:

`
The log file is: polished_assembly.44.scf0.circ.runAmos.log
Doing step 10:  Building AMOS bank & Dumping reads
Doing step 11
Doing step 12
Doing step 13
Doing step 20:  Getting overlaps 
Doing step 21
Doing step 22
Doing step 23:  Converting overlaps
Doing step 24:  Loading overlaps to the bank
Doing step 25
Doing step 30:  Running contigger
Doing step 31
Doing step 32
Doing step 40:  Running consensus
Doing step 41
Command: /software/smrtanalysis/v2.3.0.140936.p5.app/current/analysis/bin/make-consensus -B -e 0.06 -b polished_assembly.44.scf0.circ.bnk -w 15  exited with status: 1
`

The total self dotplot is attached next
![dotplot 44 all](https://cloud.githubusercontent.com/assets/16022611/19428064/7a361158-9450-11e6-80db-b206c2550b5c.png)

Below is the same self dotplot but zoomed in at the bottom-left corner (as shown in the coordinates)
![dotplot 44 bottomleft](https://cloud.githubusercontent.com/assets/16022611/19428093/a0daea5e-9450-11e6-9da4-d37df8121167.png)

**Now, the second figure shows a significant overlap but there is a shift/gap as well in region 5442146-5442706**. Please note that I have assembled twice hoping that the assembly will start randomly from another site in the chromosome but both produced an identical contigs.

Does anyone know what's going on here? and how do I fix/circularise this?

Many thanks in advance,
/SB

**Comment by rhallPB** [comment]
I believe the minimus error it likely due to the imperfect overlap. The easiest fix is probably to trim ~5000 bp from the end of the contig (removing the sequence that includes the shift) then try the circularization again, Then confirm no sequence has been lost / missasembled, by resequencing against the new circularized genome, paying particular attention to the region that was overlapped.

**Comment by mjfi2sb3** [comment]
I will try that but how about if I removed the one end that is shorter (missing parts of a couple pf genes).

**Investigations:**
I looked at the genes in the overlapping ends of the contig. The shorter one (end of contig) is missing a chunk that belongs to a phosphoglycerate mutase gene and tpiA gene both of which seem to be complete in the other end (start of contig). Therefore, would be sufficient to remove the short overlap and get this over with?

**A question:**
I am still puzzled by how this came to happen. Could it be some of the bacteria in the pure culture have lost/gained this stretch of DNA.

Best,
/SB

**Comment by rhallPB** [comment]
Yes you can simply trim one of the overlaps all the way back to the point at which it starts, but on resequencing the area of interest will be at the beginning of the contig and harder to validate. If you simply trim rather than overlap I would change the origin of the sequence also so that any issues show up. It is quite common for bacteria in pure culture to have minor populations, a simple blast of the sequence may tell you if it is something that is likely to be variable (IS element, phage insertion, etc.).

**Comment by mjfi2sb3** [comment]
Do I need to run the resequencing protocol for every genome circularisation I perform? and why?

I just did what you recommended...trimmed 10kbp of the end of the contig which removed the shifted sequence and overlapped using minimus2. It worked. I am just wondering why I need to run the resequencing protocol? (I am using the smrtpipe.py commandline version)

Many thanks for the help/tips,
/SB

**Comment by rhallPB** [comment]
I would run the resequencing to check to make sure that the overlapping is correct, it most likely is, but looking at the raw read coverage will reveal any issues. If the alternate sequence (that was trimmed), is actually the correct (most abundant) answer then the raw read coverage should reflect this. 
If you don't have to trim any sequence to get the circularization to work then it's less of an issue.

**Comment by mjfi2sb3** [comment]
thank you :-D

/SB
